import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Layout from "../layout/layout";
import { images } from "./api/testdb";
import Carousel from "../components/Carousel";

const Home: NextPage = () => {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <AuthShowcase />
      </main>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <section id="hero" className="grid grid-cols-2 p-8">
          <div>
            <h1 className=" text-6xl">We put to you awesome baranditas</h1>
            <p className="mt-10">we are a family company</p>
            <button className="btn-primary btn mt-20">Our Services</button>
          </div>
          <div></div>
        </section>

        <section id="show" className="mt-8 flex flex-col">
          <div className="flex flex-col gap-8 p-8 md:flex-row">
            <h2 className="w-full text-4xl md:w-1/2 ">
              Why baramditas is the best choice?
            </h2>
            <p className="w-full md:w-1/2">...just look at those:</p>
          </div>
          <div className=" shrink-0">
            <Carousel images={images} />
          </div>
        </section>

        <section id="services" className="mt-20 flex flex-col p-8">
          <h2 className="text-4xl">The services that whe provide for you</h2>
          <div className="mt-10 grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-8">
            <div className="flex flex-col items-center">
              <div>
                <Image
                  src={"/Icon.png"}
                  alt={"service pic"}
                  width={45}
                  height={45}
                  className="object-cover"
                />
              </div>
              <p>
                Create a platform with the best and coolest quality from us.
              </p>
            </div>
            <div className="flex flex-col items-center">
              <div>
                <Image
                  src={"/Icon.jpg"}
                  alt={"service pic"}
                  width={45}
                  height={45}
                  className="object-cover"
                />
              </div>
              <p>
                Create a platform with the best and coolest quality from us.
              </p>
            </div>
            <div className="flex flex-col items-center">
              <div>
                <Image
                  src={"/Icon (1).jpg"}
                  alt={"service pic"}
                  width={45}
                  height={45}
                  className="object-cover"
                />
              </div>
              <p>
                Create a platform with the best and coolest quality from us.
              </p>
            </div>
            <div className="flex flex-col items-center">
              <div>
                <Image
                  src={"/Icon (2).jpg"}
                  alt={"service pic"}
                  width={45}
                  height={45}
                  className="object-cover"
                />
              </div>
              <p>
                Create a platform with the best and coolest quality from us.
              </p>
            </div>
            <div className="flex flex-col items-center">
              <div>
                <Image
                  src={"/Icon (3).jpg"}
                  alt={"service pic"}
                  width={45}
                  height={45}
                  className="object-cover"
                />
              </div>
              <p>
                Create a platform with the best and coolest quality from us.
              </p>
            </div>
            <div className="flex flex-col items-center">
              <div>
                <Image
                  src={"/Icon (4).jpg"}
                  alt={"service pic"}
                  width={45}
                  height={45}
                  className="object-cover"
                />
              </div>
              <p>
                Create a platform with the best and coolest quality from us.
              </p>
            </div>
          </div>
        </section>

        <section id="about" className="mt-20 p-8">
          <h2 className="text-4xl">Somehing About Us</h2>
          <p className="mt-20">
            Lorem ipsum dolor sit amet. Rem dolor possimus ad quam libero est
            accusamus quod ea magni deserunt est dolore deleniti id quia dolore
            ut iusto aperiam. Aut consequatur corrupti aut dicta omnis ex
            eligendi voluptas et sint fugiat? Ut soluta Quis ut praesentium
            minima aut eligendi alias ab expedita earum est omnis praesentium id
            suscipit iusto sed laudantium quibusdam. Qui dolorum repellat ut
            quisquam possimus est voluptatem rerum.
          </p>
        </section>
      </Layout>
    </>
  );
};
